context:
  name: datacube-compute
  python_min: "3.10"
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/auspatious/datacube-compute/archive/${{ version }}.tar.gz
  sha256: f9bbe480778e1184261909ce164e551e5d80e80ef071aebd8257426b026e7d84

build:
  number: 0
  python:
    version_independent: true
  script:
    - if: win
      then: set MATURIN_PEP517_ARGS="--features=pyo3/abi3-py310"
      else: export MATURIN_PEP517_ARGS="--features=pyo3/abi3-py310"
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip:
    - not (match(python, python_min ~ ".*") and is_abi3)

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
    - maturin >=1.0,<2.0
  host:
    - maturin >=1.0,<2.0
    - pip
    - python ${{ python_min }}.*
    - if: is_abi3
      then:
        - python-abi3 ${{ python_min }}.*
  run:
    - numpy
    - python >=${{ python_min }}
    - xarray

tests:
  - python:
      imports:
        - datacube_compute
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - python -c "import datacube_compute; assert datacube_compute.__version__ == '${{ version }}', datacube_compute.__version__"
      - abi3audit $SP_DIR/datacube_compute/backend.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
    requirements:
      run:
        - abi3audit

about:
  summary: A library with fast implementations of algorithms for processing satellite images.
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  homepage: https://github.com/auspatious/datacube-compute

extra:
  recipe-maintainers:
    - alexgleith
    - weiji14
