context:
  name: datacube-compute
  version: "0.0.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/auspatious/datacube-compute/archive/${{ version }}.tar.gz
  sha256: a58fff99f059d0d518dfdfae971d78ce46f6ab95d7e436c43acea5130d85b4de

build:
  number: 1
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - if: win
      then: set SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }}
    - if: unix
      then: export SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }}
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - setuptools
    - setuptools-rust
    - setuptools-scm >=3.4
    - wheel
  run:
    - numpy
    - python
    - xarray

tests:
  - python:
      imports:
        - datacube_compute
      pip_check: true

about:
  summary: A library with fast implementations of algorithms for processing satellite images.
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE
  homepage: https://github.com/auspatious/datacube-compute

extra:
  recipe-maintainers:
    - alexgleith
    - weiji14
